<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Managed Shells
    |--------------------------------------------------------------------------
    |
    | These shells will be supported by the package installer.
    |
    */
    'shells' => [
        'bash',
        'zsh',
    ],

    /*
    |--------------------------------------------------------------------------
    | Backup Shell Files
    |--------------------------------------------------------------------------
    |
    | The package creates a backup before modifying any user shell file.
    |
    */
    'backup' => true,

    /*
    |--------------------------------------------------------------------------
    | Daily Favorites
    |--------------------------------------------------------------------------
    |
    | Daily favorites are rendered into the shell `daily` / `lamdaily`
    | function. Keep this empty by default, or pass --daily during install.
    |
    */
    'daily' => [],

    /*
    |--------------------------------------------------------------------------
    | Install Presets
    |--------------------------------------------------------------------------
    |
    | Presets are named bundles of alias groups. They can be installed with
    | --preset=fullstack, --preset=sail, --preset=pro, and similar options.
    |
    */
    'presets' => [
        'core' => [
            'description' => 'Core Laravel, Composer, PHP, Git, and system shortcuts.',
            'groups' => ['system', 'git', 'composer', 'php', 'artisan'],
        ],
        'fullstack' => [
            'description' => 'Daily full-stack Laravel development without Docker/Sail-only extras.',
            'groups' => ['system', 'git', 'composer', 'php', 'artisan', 'npm', 'pnpm', 'yarn', 'quality', 'security', 'workflow'],
        ],
        'sail' => [
            'description' => 'Laravel Sail lifecycle, Artisan, Composer, frontend, and quality shortcuts.',
            'groups' => ['system', 'git', 'artisan', 'sail', 'quality', 'security', 'workflow'],
        ],
        'frontend' => [
            'description' => 'npm, pnpm, Yarn, and Vite shortcuts.',
            'groups' => ['npm', 'pnpm', 'yarn'],
        ],
        'ops' => [
            'description' => 'Docker, GitHub CLI, security, and project workflow shortcuts.',
            'groups' => ['docker', 'github', 'security', 'workflow'],
        ],
        'pro' => [
            'description' => 'Everything: full-stack Laravel, Sail, Docker, GitHub CLI, security, and workflow aliases.',
            'groups' => ['system', 'git', 'github', 'docker', 'composer', 'php', 'artisan', 'sail', 'npm', 'pnpm', 'yarn', 'quality', 'security', 'workflow'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Alias Groups
    |--------------------------------------------------------------------------
    |
    | DAM-style names are the preferred aliases. Older v0.3 names stay as
    | compatibility aliases where practical.
    |
    */
    'groups' => [
        'system' => [
            'description' => 'Project-root terminal helpers.',
            'aliases' => [
                'cls' => 'clear',
                'c' => 'clear',
                'll' => 'ls -alF',
                'la' => 'ls -A',
                'lh' => 'ls -lah',
                'here' => 'pwd',
                'lpwd' => 'pwd',
                'lroot' => 'pwd',
                'md' => 'mkdir -p',
                'path' => 'printf "%s\n" "$PATH" | tr ":" "\n"',
                'whichp' => 'command -v',
                'ports' => 'lsof -i -P -n | grep LISTEN',
                'disk' => 'df -h',
                'dus' => 'du -sh',
                'mem' => 'free -h',
                'cpu' => 'top -bn1 | head -20',
                'topmem' => 'ps aux --sort=-%mem | head -10',
                'topcpu' => 'ps aux --sort=-%cpu | head -10',
                'myip' => 'hostname -I',
                'servehere' => 'python3 -m http.server',
            ],
        ],
        'git' => [
            'description' => 'Daily Git workflow shortcuts.',
            'aliases' => [
                'gst' => 'git status -sb',
                'gs' => 'git status',
                'gstatus' => 'git status',
                'ga' => 'git add',
                'gaa' => 'git add -A',
                'gb' => 'git branch',
                'gco' => 'git checkout',
                'gcb' => 'git checkout -b',
                'gc' => 'git commit',
                'gcm' => 'git commit -m',
                'gcam' => 'git add -A && git commit -m',
                'gca' => 'git commit --amend',
                'gd' => 'git diff',
                'gds' => 'git diff --staged',
                'gl' => 'git log --oneline --graph --decorate',
                'glog' => 'git log --oneline --graph --decorate --all',
                'gpl' => 'git pull',
                'gpull' => 'git pull',
                'gp' => 'git push',
                'gpush' => 'git push',
                'gpsu' => 'git push --set-upstream origin HEAD',
                'gpf' => 'git push --force-with-lease',
                'gstash' => 'git stash',
                'gstp' => 'git stash pop',
                'gbranch' => 'git branch',
                'gcommit' => 'git commit',
            ],
        ],
        'github' => [
            'description' => 'GitHub CLI shortcuts.',
            'aliases' => [
                'ghpr' => 'gh pr create',
                'ghprv' => 'gh pr view --web',
                'ghprs' => 'gh pr status',
                'ghruns' => 'gh run list',
                'ghwatch' => 'gh run watch',
            ],
        ],
        'docker' => [
            'description' => 'Docker and Docker Compose shortcuts.',
            'aliases' => [
                'dcomp' => 'docker compose',
                'dc' => 'docker compose',
                'dcu' => 'docker compose up -d',
                'dcud' => 'docker compose up -d',
                'dcub' => 'docker compose up -d --build',
                'dcd' => 'docker compose down',
                'dcl' => 'docker compose logs -f',
                'dclf' => 'docker compose logs -f',
                'dcr' => 'docker compose restart',
                'dps' => 'docker ps',
                'dpa' => 'docker ps -a',
                'dprune' => 'docker system prune -af',
                'dcbuild' => 'docker compose build',
                'dcexec' => 'docker compose exec',
                'dcsh' => 'docker compose exec app sh',
                'dcphp' => 'docker compose exec app php',
                'dcartisan' => 'docker compose exec app php artisan',
            ],
        ],
        'composer' => [
            'description' => 'Composer package manager shortcuts.',
            'aliases' => [
                'ci' => 'composer install',
                'cu' => 'composer update',
                'cr' => 'composer require',
                'creq' => 'composer require',
                'creqd' => 'composer require --dev',
                'crm' => 'composer remove',
                'cremove' => 'composer remove',
                'cda' => 'composer dump-autoload',
                'cdump' => 'composer dump-autoload',
                'cautoload' => 'composer dump-autoload',
                'cval' => 'composer validate --strict',
                'cvalidate' => 'composer validate',
                'caudit' => 'composer audit',
                'coutdated' => 'composer outdated --direct',
                'co' => 'composer outdated',
                'cs' => 'composer show',
                'cshow' => 'composer show',
                'ct' => 'composer test',
                'cwhy' => 'composer why',
                'cwhy_not' => 'composer why-not',
                'cinstall' => 'composer install',
                'cupdate' => 'composer update',
                'crequire' => 'composer require',
            ],
        ],
        'php' => [
            'description' => 'PHP runtime and inspection shortcuts.',
            'aliases' => [
                'phpv' => 'php -v',
                'phpm' => 'php -m',
                'phpi' => 'php -i',
                'pv' => 'php -v',
                'pm' => 'php -m',
                'pi' => 'php -i',
                'psy' => 'php artisan tinker',
            ],
        ],
        'artisan' => [
            'description' => 'Laravel Artisan, database, queue, log, and generator shortcuts.',
            'aliases' => [
                'art' => 'php artisan',
                'artisan' => 'php artisan',
                'pa' => 'php artisan',
                'serve' => 'php artisan serve',
                'lserve' => 'php artisan serve',
                'myroutes' => 'php artisan route:list',
                'routes' => 'php artisan route:list',
                'lroutes' => 'php artisan route:list',
                'about' => 'php artisan about',
                'tinker' => 'php artisan tinker',
                'ltinker' => 'php artisan tinker',
                'clearcache' => 'php artisan optimize:clear',
                'lclear' => 'php artisan optimize:clear',
                'optimize' => 'php artisan optimize',
                'loptimize' => 'php artisan optimize',
                'configcache' => 'php artisan config:cache',
                'routecache' => 'php artisan route:cache',
                'viewclear' => 'php artisan view:clear',
                'lviewclear' => 'php artisan view:clear',
                'storage' => 'php artisan storage:link',
                'lstorage' => 'php artisan storage:link',
                'sailinstall' => 'php artisan sail:install',
                'dbmigrate' => 'php artisan migrate',
                'lmigrate' => 'php artisan migrate',
                'dbfresh' => 'php artisan migrate:fresh --seed',
                'lfresh' => 'php artisan migrate:fresh',
                'lfreshseed' => 'php artisan migrate:fresh --seed',
                'dbseed' => 'php artisan db:seed',
                'lseed' => 'php artisan db:seed',
                'dbrollback' => 'php artisan migrate:rollback',
                'lrollback' => 'php artisan migrate:rollback',
                'dbstatus' => 'php artisan migrate:status',
                'lmstatus' => 'php artisan migrate:status',
                'qwork' => 'php artisan queue:work',
                'lqueue' => 'php artisan queue:work',
                'qlisten' => 'php artisan queue:listen',
                'qrestart' => 'php artisan queue:restart',
                'qfailed' => 'php artisan queue:failed',
                'qretry' => 'php artisan queue:retry all',
                'logs' => 'tail -f storage/logs/laravel.log',
                'llog' => 'tail -f storage/logs/laravel.log',
                'logclear' => ': > storage/logs/laravel.log && echo "Laravel log cleared."',
                'mkc' => 'php artisan make:controller',
                'mkci' => 'php artisan make:controller --invokable',
                'mkcr' => 'php artisan make:controller --resource',
                'mkm' => 'php artisan make:model',
                'mkmig' => 'php artisan make:migration',
                'mkf' => 'php artisan make:factory',
                'mks' => 'php artisan make:seeder',
                'mkreq' => 'php artisan make:request',
                'mkres' => 'php artisan make:resource',
                'mktest' => 'php artisan make:test',
                'mktestu' => 'php artisan make:test --unit',
                'mkmid' => 'php artisan make:middleware',
                'mkjob' => 'php artisan make:job',
                'mkevent' => 'php artisan make:event',
                'mklistener' => 'php artisan make:listener',
                'mkmail' => 'php artisan make:mail',
                'mkpolicy' => 'php artisan make:policy',
                'mkcommand' => 'php artisan make:command',
                'mcontroller' => 'php artisan make:controller',
                'mmodel' => 'php artisan make:model',
                'mmigration' => 'php artisan make:migration',
                'mrequest' => 'php artisan make:request',
                'mresource' => 'php artisan make:resource',
                'mpolicy' => 'php artisan make:policy',
                'mjob' => 'php artisan make:job',
                'mcommand' => 'php artisan make:command',
                'mevent' => 'php artisan make:event',
                'mlistener' => 'php artisan make:listener',
                'mnotification' => 'php artisan make:notification',
                'mmail' => 'php artisan make:mail',
                'mfactory' => 'php artisan make:factory',
                'mseeder' => 'php artisan make:seeder',
                'mtest' => 'php artisan make:test',
            ],
        ],
        'sail' => [
            'description' => 'Laravel Sail lifecycle, Artisan, Composer, frontend, and quality shortcuts.',
            'aliases' => [
                'sail' => './vendor/bin/sail',
                'sup' => './vendor/bin/sail up -d',
                'devup' => './vendor/bin/sail up -d',
                'supb' => './vendor/bin/sail up -d --build',
                'sbuild' => './vendor/bin/sail build --no-cache',
                'sdown' => './vendor/bin/sail down',
                'sd' => './vendor/bin/sail down',
                'sdownv' => './vendor/bin/sail down -v',
                'sstop' => './vendor/bin/sail stop',
                'srestart' => './vendor/bin/sail restart',
                'sr' => './vendor/bin/sail restart',
                'sps' => './vendor/bin/sail ps',
                'slog' => './vendor/bin/sail logs -f',
                'slogs' => './vendor/bin/sail logs -f',
                'sshell' => './vendor/bin/sail shell',
                'sroot' => './vendor/bin/sail root-shell',
                'smysql' => './vendor/bin/sail mysql',
                'sredis' => './vendor/bin/sail redis',
                'sart' => './vendor/bin/sail artisan',
                'sa' => './vendor/bin/sail artisan',
                'sroutes' => './vendor/bin/sail artisan route:list',
                'sarl' => './vendor/bin/sail artisan route:list',
                'sabout' => './vendor/bin/sail artisan about',
                'sclearcache' => './vendor/bin/sail artisan optimize:clear',
                'saoc' => './vendor/bin/sail artisan optimize:clear',
                'stinker' => './vendor/bin/sail artisan tinker',
                'satk' => './vendor/bin/sail artisan tinker',
                'smig' => './vendor/bin/sail artisan migrate',
                'sam' => './vendor/bin/sail artisan migrate',
                'smfs' => './vendor/bin/sail artisan migrate:fresh --seed',
                'samfs' => './vendor/bin/sail artisan migrate:fresh --seed',
                'sseed' => './vendor/bin/sail artisan db:seed',
                'sphp' => './vendor/bin/sail php',
                'scomposer' => './vendor/bin/sail composer',
                'sc' => './vendor/bin/sail composer',
                'sci' => './vendor/bin/sail composer install',
                'scu' => './vendor/bin/sail composer update',
                'scr' => './vendor/bin/sail composer require',
                'snpm' => './vendor/bin/sail npm',
                'sn' => './vendor/bin/sail npm',
                'sni' => './vendor/bin/sail npm install',
                'snpx' => './vendor/bin/sail npx',
                'syarn' => './vendor/bin/sail yarn',
                'sy' => './vendor/bin/sail yarn',
                'snrd' => './vendor/bin/sail npm run dev',
                'snd' => './vendor/bin/sail npm run dev',
                'snrb' => './vendor/bin/sail npm run build',
                'snb' => './vendor/bin/sail npm run build',
                'snrt' => './vendor/bin/sail npm run typecheck',
                'snrl' => './vendor/bin/sail npm run lint',
                'spnpm' => './vendor/bin/sail pnpm',
                'spnpi' => './vendor/bin/sail pnpm install',
                'spnpd' => './vendor/bin/sail pnpm dev',
                'syd' => './vendor/bin/sail yarn dev',
                'spest' => './vendor/bin/sail php vendor/bin/pest',
                'spestf' => './vendor/bin/sail php vendor/bin/pest --filter',
                'sphpunit' => './vendor/bin/sail php vendor/bin/phpunit',
                'spint' => './vendor/bin/sail php vendor/bin/pint',
                'spinttest' => './vendor/bin/sail php vendor/bin/pint --test',
                'srector' => './vendor/bin/sail php vendor/bin/rector process',
                'srcheck' => './vendor/bin/sail php vendor/bin/rector process --dry-run',
                'sstan' => './vendor/bin/sail php vendor/bin/phpstan analyse',
                'stest' => './vendor/bin/sail php vendor/bin/pest',
                'sqa' => 'spint && srcheck && sstan && spest',
                'smkc' => './vendor/bin/sail artisan make:controller',
                'smkci' => './vendor/bin/sail artisan make:controller --invokable',
                'smkcr' => './vendor/bin/sail artisan make:controller --resource',
                'smkm' => './vendor/bin/sail artisan make:model',
                'smkmig' => './vendor/bin/sail artisan make:migration',
                'smkf' => './vendor/bin/sail artisan make:factory',
                'smks' => './vendor/bin/sail artisan make:seeder',
                'smkreq' => './vendor/bin/sail artisan make:request',
                'smkres' => './vendor/bin/sail artisan make:resource',
                'smktest' => './vendor/bin/sail artisan make:test',
                'smktestu' => './vendor/bin/sail artisan make:test --unit',
                'smkmid' => './vendor/bin/sail artisan make:middleware',
                'smkjob' => './vendor/bin/sail artisan make:job',
                'smkevent' => './vendor/bin/sail artisan make:event',
                'smklistener' => './vendor/bin/sail artisan make:listener',
                'smkmail' => './vendor/bin/sail artisan make:mail',
                'smkpolicy' => './vendor/bin/sail artisan make:policy',
                'smkcommand' => './vendor/bin/sail artisan make:command',
                'sailup' => './vendor/bin/sail up',
                'sailupd' => './vendor/bin/sail up -d',
                'saildown' => './vendor/bin/sail down',
                'sailrestart' => './vendor/bin/sail restart',
                'sailshell' => './vendor/bin/sail shell',
                'sailroot' => './vendor/bin/sail root-shell',
                'sailartisan' => './vendor/bin/sail artisan',
                'sailtest' => './vendor/bin/sail artisan test',
                'sailmigrate' => './vendor/bin/sail artisan migrate',
                'sailfresh' => './vendor/bin/sail artisan migrate:fresh',
                'sailfreshseed' => './vendor/bin/sail artisan migrate:fresh --seed',
                'sailcomposer' => './vendor/bin/sail composer',
                'sailnpm' => './vendor/bin/sail npm',
                'saildev' => './vendor/bin/sail npm run dev',
                'sailbuild' => './vendor/bin/sail npm run build',
                'saillogs' => './vendor/bin/sail logs -f',
            ],
        ],
        'npm' => [
            'description' => 'npm and Vite frontend workflow shortcuts.',
            'aliases' => [
                'n' => 'npm',
                'ni' => 'npm install',
                'nrd' => 'npm run dev',
                'nd' => 'npm run dev',
                'ndev' => 'npm run dev',
                'vite' => 'npm run dev',
                'nrb' => 'npm run build',
                'nb' => 'npm run build',
                'nbuild' => 'npm run build',
                'nrt' => 'npm run typecheck',
                'nrl' => 'npm run lint',
                'nl' => 'npm run lint',
                'nlint' => 'npm run lint',
                'nrf' => 'npm run format',
                'nf' => 'npm run format',
                'nformat' => 'npm run format',
                'npreview' => 'npm run preview',
                'np' => 'npm run preview',
                'nt' => 'npm test',
                'ntest' => 'npm test',
                'naudit' => 'npm audit',
                'noutdated' => 'npm outdated',
            ],
        ],
        'pnpm' => [
            'description' => 'pnpm frontend workflow shortcuts.',
            'aliases' => [
                'pn' => 'pnpm',
                'pni' => 'pnpm install',
                'pnd' => 'pnpm dev',
                'pndev' => 'pnpm dev',
                'pnb' => 'pnpm build',
                'pnbuild' => 'pnpm build',
                'pnp' => 'pnpm preview',
                'pnpreview' => 'pnpm preview',
                'pnt' => 'pnpm test',
                'pntest' => 'pnpm test',
                'pnl' => 'pnpm lint',
                'pnlint' => 'pnpm lint',
                'pnformat' => 'pnpm format',
                'pnadd' => 'pnpm add',
                'pnremove' => 'pnpm remove',
            ],
        ],
        'yarn' => [
            'description' => 'Yarn frontend workflow shortcuts.',
            'aliases' => [
                'y' => 'yarn',
                'yi' => 'yarn install',
                'yd' => 'yarn dev',
                'ydev' => 'yarn dev',
                'yb' => 'yarn build',
                'ybuild' => 'yarn build',
                'yp' => 'yarn preview',
                'ypreview' => 'yarn preview',
                'yt' => 'yarn test',
                'ytest' => 'yarn test',
                'yl' => 'yarn lint',
                'ylint' => 'yarn lint',
                'yformat' => 'yarn format',
                'yadd' => 'yarn add',
                'yremove' => 'yarn remove',
            ],
        ],
        'quality' => [
            'description' => 'Pest, Pint, Rector, PHPStan, and full quality pipelines.',
            'aliases' => [
                'pint' => './vendor/bin/pint',
                'pinttest' => './vendor/bin/pint --test',
                'pintd' => './vendor/bin/pint --dirty',
                'pest' => './vendor/bin/pest',
                'pestf' => './vendor/bin/pest --filter',
                'pestcov' => './vendor/bin/pest --coverage',
                'phpunit' => './vendor/bin/phpunit',
                'rcheck' => './vendor/bin/rector process --dry-run',
                'rfix' => './vendor/bin/rector process',
                'rector' => './vendor/bin/rector process',
                'rectord' => './vendor/bin/rector process --dry-run',
                'stan' => './vendor/bin/phpstan analyse',
                'stanmax' => './vendor/bin/phpstan analyse --memory-limit=1G',
                'qa' => './vendor/bin/pint && ./vendor/bin/rector process --dry-run && ./vendor/bin/phpstan analyse && ./vendor/bin/pest',
                'quality' => 'composer quality',
                'cq' => 'composer quality',
                'qtest' => './vendor/bin/pest',
                'qtestf' => './vendor/bin/pest --filter',
                'qfix' => './vendor/bin/pint',
                'qdirty' => './vendor/bin/pint --dirty',
                'qstan' => './vendor/bin/phpstan analyse',
                'qrector' => './vendor/bin/rector process',
                'qrectord' => './vendor/bin/rector process --dry-run',
            ],
        ],
        'security' => [
            'description' => 'Laravel project safety checks.',
            'aliases' => [
                'secenv' => '[ -f .env ] && echo ".env exists" || echo ".env missing"; git ls-files --error-unmatch .env >/dev/null 2>&1 && echo "WARNING: .env is tracked by git" || echo ".env is not tracked by git"',
                'seckey' => 'php artisan key:generate --show',
                'secaudit' => 'composer audit',
                'secnpm' => 'npm audit',
                'secperms' => 'ls -ld storage bootstrap/cache',
            ],
        ],
        'workflow' => [
            'description' => 'Project doctor, start, stop, and quality workflow shortcuts.',
            'aliases' => [
                'doctor' => 'php artisan about',
                'projectdoctor' => 'php artisan about',
                'start' => 'if [ -f ./vendor/bin/sail ]; then ./vendor/bin/sail up -d; elif [ -f package.json ]; then npm run dev; else php artisan serve; fi',
                'stop' => 'if [ -f ./vendor/bin/sail ]; then ./vendor/bin/sail down; else echo "No Sail stop command found."; fi',
                'devflow' => 'php artisan about && { [ -f package.json ] && npm run dev || true; }',
                'checkall' => 'qa',
            ],
        ],
    ],
];
