<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Managed Shells
    |--------------------------------------------------------------------------
    |
    | These shells will be supported by the package installer. The first
    | implementation will focus on safe Bash and Zsh configuration updates.
    |
    */
    'shells' => [
        'bash',
        'zsh',
    ],

    /*
    |--------------------------------------------------------------------------
    | Backup Shell Files
    |--------------------------------------------------------------------------
    |
    | The package should create a backup before modifying any user shell file.
    |
    */
    'backup' => true,

    /*
    |--------------------------------------------------------------------------
    | Alias Groups
    |--------------------------------------------------------------------------
    |
    | These groups define the built-in alias catalog. Installed aliases are
    | rendered through a Laravel-project guard before any command runs.
    |
    */
    'groups' => [
        'system' => [
            'description' => 'Laravel project terminal helpers.',
            'aliases' => [
                'c' => 'clear',
                'll' => 'ls -lah',
                'la' => 'ls -la',
                'lpwd' => 'pwd',
                'lroot' => 'pwd',
                'md' => 'mkdir -p',
            ],
        ],
        'git' => [
            'description' => 'Git workflow shortcuts.',
            'aliases' => [
                'gs' => 'git status',
                'ga' => 'git add',
                'gaa' => 'git add .',
                'gb' => 'git branch',
                'gco' => 'git checkout',
                'gcb' => 'git checkout -b',
                'gc' => 'git commit',
                'gcm' => 'git commit -m',
                'gca' => 'git commit --amend',
                'gd' => 'git diff',
                'gds' => 'git diff --staged',
                'gl' => 'git log --oneline --graph --decorate',
                'glog' => 'git log --oneline --graph --decorate',
                'gpl' => 'git pull',
                'gp' => 'git push',
                'gpsu' => 'git push --set-upstream origin HEAD',
                'gst' => 'git stash',
                'gstp' => 'git stash pop',
                'gstatus' => 'git status',
                'gbranch' => 'git branch',
                'gcommit' => 'git commit',
                'gpull' => 'git pull',
                'gpush' => 'git push',
            ],
        ],
        'composer' => [
            'description' => 'Composer package manager shortcuts.',
            'aliases' => [
                'ci' => 'composer install',
                'cu' => 'composer update',
                'cr' => 'composer require',
                'crm' => 'composer remove',
                'cdump' => 'composer dump-autoload',
                'co' => 'composer outdated',
                'cs' => 'composer show',
                'ct' => 'composer test',
                'cinstall' => 'composer install',
                'cupdate' => 'composer update',
                'crequire' => 'composer require',
                'cremove' => 'composer remove',
                'cautoload' => 'composer dump-autoload',
                'coutdated' => 'composer outdated',
                'cshow' => 'composer show',
                'cvalidate' => 'composer validate',
            ],
        ],
        'php' => [
            'description' => 'PHP runtime and dependency inspection shortcuts.',
            'aliases' => [
                'pv' => 'php -v',
                'pm' => 'php -m',
                'pi' => 'php -i',
                'psy' => 'php artisan tinker',
                'phpv' => 'php -v',
                'phpm' => 'php -m',
                'phpi' => 'php -i',
            ],
        ],
        'artisan' => [
            'description' => 'Laravel Artisan shortcuts.',
            'aliases' => [
                'pa' => 'php artisan',
                'art' => 'php artisan',
                'artisan' => 'php artisan',
                'pas' => 'php artisan serve',
                'pat' => 'php artisan test',
                'pati' => 'php artisan tinker',
                'pam' => 'php artisan migrate',
                'pamf' => 'php artisan migrate:fresh',
                'pamfs' => 'php artisan migrate:fresh --seed',
                'pads' => 'php artisan db:seed',
                'paq' => 'php artisan queue:work',
                'pasch' => 'php artisan schedule:work',
                'pac' => 'php artisan cache:clear',
                'pacc' => 'php artisan config:clear',
                'parc' => 'php artisan route:clear',
                'pavc' => 'php artisan view:clear',
                'pao' => 'php artisan optimize',
                'paoc' => 'php artisan optimize:clear',
                'parl' => 'php artisan route:list',
                'paml' => 'php artisan make:livewire',
                'pamc' => 'php artisan make:controller',
                'pamm' => 'php artisan make:model',
                'pammi' => 'php artisan make:migration',
                'lserve' => 'php artisan serve',
                'ltest' => 'php artisan test',
                'ltinker' => 'php artisan tinker',
                'lmigrate' => 'php artisan migrate',
                'lfresh' => 'php artisan migrate:fresh',
                'lfreshseed' => 'php artisan migrate:fresh --seed',
                'lseed' => 'php artisan db:seed',
                'lrollback' => 'php artisan migrate:rollback',
                'lmstatus' => 'php artisan migrate:status',
                'lqueue' => 'php artisan queue:work',
                'lqueueonce' => 'php artisan queue:work --once',
                'lschedule' => 'php artisan schedule:work',
                'lcache' => 'php artisan cache:clear',
                'lconfig' => 'php artisan config:clear',
                'lrouteclear' => 'php artisan route:clear',
                'lviewclear' => 'php artisan view:clear',
                'lclear' => 'php artisan optimize:clear',
                'loptimize' => 'php artisan optimize',
                'lroutes' => 'php artisan route:list',
                'levents' => 'php artisan event:list',
                'lstorage' => 'php artisan storage:link',
                'lkey' => 'php artisan key:generate',
                'llog' => 'tail -f storage/logs/laravel.log',
                'mcontroller' => 'php artisan make:controller',
                'mmodel' => 'php artisan make:model',
                'mmigration' => 'php artisan make:migration',
                'mrequest' => 'php artisan make:request',
                'mresource' => 'php artisan make:resource',
                'mpolicy' => 'php artisan make:policy',
                'mjob' => 'php artisan make:job',
                'mcommand' => 'php artisan make:command',
                'mevent' => 'php artisan make:event',
                'mlistener' => 'php artisan make:listener',
                'mnotification' => 'php artisan make:notification',
                'mmail' => 'php artisan make:mail',
                'mfactory' => 'php artisan make:factory',
                'mseeder' => 'php artisan make:seeder',
                'mtest' => 'php artisan make:test',
            ],
        ],
        'sail' => [
            'description' => 'Laravel Sail shortcuts.',
            'aliases' => [
                'sail' => './vendor/bin/sail',
                'sau' => './vendor/bin/sail up',
                'saud' => './vendor/bin/sail up -d',
                'sd' => './vendor/bin/sail down',
                'sr' => './vendor/bin/sail restart',
                'sshell' => './vendor/bin/sail shell',
                'sroot' => './vendor/bin/sail root-shell',
                'sa' => './vendor/bin/sail artisan',
                'sat' => './vendor/bin/sail artisan test',
                'sam' => './vendor/bin/sail artisan migrate',
                'samf' => './vendor/bin/sail artisan migrate:fresh',
                'samfs' => './vendor/bin/sail artisan migrate:fresh --seed',
                'satk' => './vendor/bin/sail artisan tinker',
                'saoc' => './vendor/bin/sail artisan optimize:clear',
                'sarl' => './vendor/bin/sail artisan route:list',
                'sc' => './vendor/bin/sail composer',
                'sci' => './vendor/bin/sail composer install',
                'scu' => './vendor/bin/sail composer update',
                'scr' => './vendor/bin/sail composer require',
                'sn' => './vendor/bin/sail npm',
                'sni' => './vendor/bin/sail npm install',
                'snd' => './vendor/bin/sail npm run dev',
                'snb' => './vendor/bin/sail npm run build',
                'spnpm' => './vendor/bin/sail pnpm',
                'spnpi' => './vendor/bin/sail pnpm install',
                'spnpd' => './vendor/bin/sail pnpm dev',
                'sy' => './vendor/bin/sail yarn',
                'syd' => './vendor/bin/sail yarn dev',
                'sphp' => './vendor/bin/sail php',
                'spest' => './vendor/bin/sail pest',
                'spint' => './vendor/bin/sail pint',
                'sstan' => './vendor/bin/sail phpstan',
                'slogs' => './vendor/bin/sail logs',
                'sailup' => './vendor/bin/sail up',
                'sailupd' => './vendor/bin/sail up -d',
                'saildown' => './vendor/bin/sail down',
                'sailrestart' => './vendor/bin/sail restart',
                'sailshell' => './vendor/bin/sail shell',
                'sailroot' => './vendor/bin/sail root-shell',
                'sailartisan' => './vendor/bin/sail artisan',
                'sailtest' => './vendor/bin/sail artisan test',
                'sailmigrate' => './vendor/bin/sail artisan migrate',
                'sailfresh' => './vendor/bin/sail artisan migrate:fresh',
                'sailfreshseed' => './vendor/bin/sail artisan migrate:fresh --seed',
                'sailcomposer' => './vendor/bin/sail composer',
                'sailnpm' => './vendor/bin/sail npm',
                'saildev' => './vendor/bin/sail npm run dev',
                'sailbuild' => './vendor/bin/sail npm run build',
                'saillogs' => './vendor/bin/sail logs',
            ],
        ],
        'npm' => [
            'description' => 'npm and Vite shortcuts.',
            'aliases' => [
                'n' => 'npm',
                'ni' => 'npm install',
                'nd' => 'npm run dev',
                'nb' => 'npm run build',
                'np' => 'npm run preview',
                'nt' => 'npm test',
                'nl' => 'npm run lint',
                'nf' => 'npm run format',
                'ndev' => 'npm run dev',
                'nbuild' => 'npm run build',
                'npreview' => 'npm run preview',
                'ntest' => 'npm test',
                'nlint' => 'npm run lint',
                'nformat' => 'npm run format',
                'naudit' => 'npm audit',
                'noutdated' => 'npm outdated',
            ],
        ],
        'pnpm' => [
            'description' => 'pnpm frontend workflow shortcuts.',
            'aliases' => [
                'pn' => 'pnpm',
                'pni' => 'pnpm install',
                'pnd' => 'pnpm dev',
                'pnb' => 'pnpm build',
                'pnp' => 'pnpm preview',
                'pnt' => 'pnpm test',
                'pnl' => 'pnpm lint',
                'pndev' => 'pnpm dev',
                'pnbuild' => 'pnpm build',
                'pnpreview' => 'pnpm preview',
                'pntest' => 'pnpm test',
                'pnlint' => 'pnpm lint',
                'pnformat' => 'pnpm format',
                'pnadd' => 'pnpm add',
                'pnremove' => 'pnpm remove',
            ],
        ],
        'yarn' => [
            'description' => 'Yarn frontend workflow shortcuts.',
            'aliases' => [
                'y' => 'yarn',
                'yi' => 'yarn install',
                'yd' => 'yarn dev',
                'yb' => 'yarn build',
                'yp' => 'yarn preview',
                'yt' => 'yarn test',
                'yl' => 'yarn lint',
                'ydev' => 'yarn dev',
                'ybuild' => 'yarn build',
                'ypreview' => 'yarn preview',
                'ytest' => 'yarn test',
                'ylint' => 'yarn lint',
                'yformat' => 'yarn format',
                'yadd' => 'yarn add',
                'yremove' => 'yarn remove',
            ],
        ],
        'quality' => [
            'description' => 'Laravel and PHP quality tool shortcuts.',
            'aliases' => [
                'pest' => './vendor/bin/pest',
                'pestf' => './vendor/bin/pest --filter',
                'pint' => './vendor/bin/pint',
                'pintd' => './vendor/bin/pint --dirty',
                'stan' => './vendor/bin/phpstan analyse',
                'rector' => './vendor/bin/rector',
                'rectord' => './vendor/bin/rector --dry-run',
                'cq' => 'composer quality',
                'qtest' => './vendor/bin/pest',
                'qtestf' => './vendor/bin/pest --filter',
                'qfix' => './vendor/bin/pint',
                'qdirty' => './vendor/bin/pint --dirty',
                'qstan' => './vendor/bin/phpstan analyse',
                'qrector' => './vendor/bin/rector',
                'qrectord' => './vendor/bin/rector --dry-run',
                'quality' => 'composer quality',
            ],
        ],
        'docker' => [
            'description' => 'Docker Compose shortcuts for local services.',
            'aliases' => [
                'dc' => 'docker compose',
                'dcu' => 'docker compose up',
                'dcud' => 'docker compose up -d',
                'dcd' => 'docker compose down',
                'dcr' => 'docker compose restart',
                'dcl' => 'docker compose logs',
                'dclf' => 'docker compose logs -f',
                'dps' => 'docker compose ps',
                'dcbuild' => 'docker compose build',
                'dcexec' => 'docker compose exec',
                'dcsh' => 'docker compose exec app sh',
                'dcphp' => 'docker compose exec app php',
                'dcartisan' => 'docker compose exec app php artisan',
            ],
        ],
    ],
];
